[package]

name = "db-key"
version = "0.0.5"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]

description = "A datatype intended to be used as a database key."

readme = "README.md"

license = "MIT"

[dev-dependencies]
libc = "*"